version: '3.8'

services:

  mvc-web:
    build: ./mvc-web
    container_name: mvc-web
    ports:
      - "8088:8080"
    depends_on:
      - servicio-calculo
      - servicio-libros
      - servicio-calificaciones
    networks:
      - red-interna

  servicio-libros:
    build: ./servicio-libros
    container_name: servicio-libros
    ports:
      - "8083:8080"
    networks:
      - red-interna

  servicio-calculo:
    build: ./servicio-calculo
    container_name: servicio-calculo
    ports:
      - "8082:8080"
    networks:
      - red-interna
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  servicio-calificaciones:
    build: ./servicio-calificaciones
    container_name: servicio-calificaciones
    ports:
      - "8081:8080"
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge
