version: '3.8'

services:

  mvc-web:
    build: ./mvc-web
    container_name: mvc-web
    ports:
      - "8088:8080"
    depends_on:
      - servicio-libros
      - servicio-calificaciones
    networks:
      - red-interna

  servicio-libros:
    build: ./servicio-libros
    container_name: servicio-libros
    ports:
      - "8083:8080"
    networks:
      - red-interna

  servicio-calificaciones:
    build: ./servicio-calificaciones
    container_name: servicio-calificaciones
    ports:
      - "8081:8080"
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge
